### ISSUE TITLE
Convert YAML fields to flags

### ISSUE THREAD

**Issue by knabben** [kubernetes-sigs/windows-operational-readiness#8]
Having a list of tests with common groups we should be able to pick a subset via flags filtering, to illustrate:

```
tests:
  - group: "csi"
  - group: "csi"
  - group: "hostprocess"
```

`--windows.csi` should return the first ones.
`--windows.csi --windows.hostprocess` should return all
`--windows.CSI` should return the first ones.
`` no flags should return all
